title: ğ•ğ¢ğ¬ğ¢ğ¨ğ§
email: nano@seven-labs.com
description: Now Feat. 2024 Easter Eggs! ğŸ‘½ 
baseurl: "" 
url: "https://www.waltontech.org" 
twitter_username: nano11bravo
github_username:  nano11bravo
author:
  name:  Nano11Bravo
  email: nano@seven-labs.com
  social:
    email: nano@seven-labs.com
    github: nano11bravo
    twitter: nano11bravo
    youtube: https://www.youtube.com/@nano11bravo

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)

menu:
  - title: About Me
    url:   /about/
  - title: Codespace
    url:   /codespace/
  - title: Resume
    url:   /resume/
  - title: Reviews
    url:   /reviews/
  - title: Social
    url:   /social/

remote_theme: "hydecorp/hydejack"

plugins:
  - jekyll-feed
  - jekyll-include-cache